### ISSUE TITLE
Does shaka player support 8K?

### ISSUE THREAD

**Issue by olooko** [webOS-TV-app-samples/MediaPlayback#1]
Does shaka player support 8K on webOS TV 6.0? 
I currently have the 75QNED95 (8K) model.

**Comment by ghost** [comment]
Hi, @olooko 
You can check the supported video codec for 8K UHD [here](https://webostv.developer.lge.com/develop/specifications/video-audio-60#maximum-data-transmission-rate).
If you have more questions about platform specifications, I recommend to use the [webOS TV Community](https://forum.webostv.developer.lge.com/).
Thanks.
