### ISSUE TITLE
Status of MPEG-DASH support?

### ISSUE THREAD

**Issue by Christophe-google** [webOS-TV-app-samples/MediaPlayback#2]
Hi,

The documentation (https://webostv.developer.lge.com/develop/specifications/streaming-protocol-drm) states that "Media and DRM formats that are unmentioned in this article are not supported or not recommended for use in the webOS TV platform."

MPEG-DASH is not mentioned in this article, yet the code sample does use MPEG-DASH streams. 

Can you please clarify the support for MPEG-DASH on webTV OS. 

Thanks,
Christophe

**Comment by ghost** [comment]
Hi, @Christophe-google 

As you said, MPEG-DASH is not officially supported in the webOS TV.
This media sample is working but there might be some unsupported features.
webOS TV will not support unexpected errors using MPEG-DASH.
If you have more questions about platform specifications, please use [webOS TV forum](https://forum.webostv.developer.lge.com/).

Thanks.
