### ISSUE TITLE
hls media encryption

### ISSUE THREAD

**Issue by naveenjangra2** [webOS-TV-app-samples/MediaPlayback#4]
webOs Aes 128 bit media encrypted videos are not working

**Comment by haeunp** [comment]
Hi, @naveenjangra2
You can check streaming protocol and DRM specification in [webOS TV developer site](https://webostv.developer.lge.com/develop/specifications/streaming-protocol-drm#streaming-protocol-drm-combination).
If you have any more question, please use [webOS TV Community](https://forum.webostv.developer.lge.com/).
Thanks.

**Comment by haeun-p** [comment]
Hi, @naveenjangra2
You can check streaming protocol and DRM specification in [webOS TV developer site](https://webostv.developer.lge.com/develop/specifications/streaming-protocol-drm#streaming-protocol-drm-combination).
If you have any more question, please use [webOS TV Community](https://forum.webostv.developer.lge.com/).
Thanks.
